[package]
name = "ysyncd"
version.workspace = true
edition.workspace = true

[dependencies]
ysync-core = { path = "../ysync-core" }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
libc = { workspace = true }
dirs = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
clap = { version = "4", features = ["derive"] }
signal-hook = "0.3"
tiny_http = "0.12"
filetime = "0.2"
urlencoding = "2"
regex = { workspace = true }
notify = { workspace = true }
proptest = "1"
