[package]
name = "ysync-desktop"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-autostart = "2"
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
ysync-core = { path = "../../rust/ysync-core" }
