[package]
name = "ysync-server-rs"
version.workspace = true
edition.workspace = true

[dependencies]
ysync-core = { path = "../ysync-core" }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
tiny_http = { workspace = true }
libc = { workspace = true }
signal-hook = "0.3"
argon2 = "0.5"
urlencoding = "2"
uuid = { version = "1", features = ["v4"] }
time = "0.3"
